neato_max_speed = 0.3;
neato_min_speed = -0.3;
wheel_dist = 0.245;

syms u t

u_range = [0, 3.2];

rainbow_road_center_line = [
            0.3960 * cos(2.65 * (u + 1.4)), ...
            -0.99 * sin(u + 1.4)
];

rainbow_road_center_line_vel = [
    diff(ranbow_road_center_line(1)), ...
    diff(rainbow_road_center_line(2))
];

rainbow_road_center_line_speed = magnitude(rainbow_road_center_line_vel);

rainbow_road_center_line_tangent_vec = rainbow_road_center_line_vel ./ ...
                                        rainbow_road_center_line_speed;

rainbow_road_center_line_tangent_vec_deriv = diff( ...
                                    rainbow_road_center_line_tangent_vec);
rainbow_road_center_line_norm_vec = ...
                     rainbow_road_center_line_tangent_vec_deriv ./ ...
                     magnitude(rainbow_road_center_line_tangent_vec_deriv);

tangent_vec_3d = [ ...
    rainbow_road_center_line_tangent_vec(1), ...
    rainbow_road_center_line_tangent_vec(2), ...
    0 ...
];
tangent_vec_3d_deriv = diff(tangent_vec_3d);

rainbow_road_axis_of_rotation = cross(tangent_vec_3d, tangent_vec_deriv);
rainbow_road_angular_velocity(u) = magnitude( ...
                                            rainbow_road_axis_of_rotation);

rainbow_road_vel_left = (rainbow_road_center_line_vel - ...
            (wheel_dist / 2) * rainbow_road_angular_velocity) .* ...
             rainbow_road_center_line_tangent_vec;

rainbow_road_vel_right = (rainbow_road_center_line_vel + ...
            (wheel_dist / 2) * rainbow_road_angular_velocity) .* ...
            rainbow_road_center_line_tangent_vec;
